# Generated by Django 3.1.1 on 2020-09-20 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=10000)),
                ('noteMaker', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='contacts.contact')),
            ],
        ),
    ]
