# Generated by Django 3.1.1 on 2020-09-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='noteMaker',
        ),
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.ForeignKey(
                default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='contacts.note'),
        ),
    ]
