# Generated by Django 3.1.1 on 2020-09-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200920_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='contacts.note'),
        ),
    ]
